src/quizsite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("quizzes.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

src/quizzes/urls.py
from django.urls import path

from . import views

app_name = "quizzes"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("quizzes/<int:quiz_id>/", views.display_quiz, name="display_quiz"),
    path("quizzes/<int:quiz_id>/questions/<int:question_id>", views.display_question, name="display_question"),
    path("questions/<int:question_id>/grade/", views.grade_question, name="grade_question"),
]

src/quizzes/models.py
import typing

from django.contrib.postgres import fields
from django.db import models


class Quiz(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    prompt = models.CharField(max_length=200)

    def __str__(self):
        return self.prompt

    def get_answer(self) -> typing.Union["Answer", None]:
        return getattr(self, "multiplechoiceanswer", None) or getattr(self, "freetextanswer", None)


class Answer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    correct_answer = models.CharField(max_length=200)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.correct_answer

    def is_correct(self, user_answer) -> bool:
        return user_answer == self.correct_answer


class FreeTextAnswer(Answer):
    case_sensitive = models.BooleanField(default=False)

    def is_correct(self, user_answer) -> bool:
        if not self.case_sensitive:
            return user_answer.lower() == self.correct_answer.lower()
        return user_answer == self.correct_answer


class MultipleChoiceAnswer(Answer):
    choices = fields.ArrayField(models.CharField(max_length=200, blank=True))

    def __str__(self) -> str:
        return f"{self.correct_answer} from {self.choices}"

src/quizzes/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic

from .models import Question, Quiz


class IndexView(generic.ListView):
    model = Quiz
    template_name = "quizzes/index.html"


def display_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = quiz.question_set.first()
    return redirect(reverse("quizzes:display_question", kwargs={"quiz_id": quiz_id, "question_id": question.pk}))


def display_question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    # fetch ALL of the questions to find current and next question
    questions = quiz.question_set.all()
    current_question, next_question = None, None
    for ind, question in enumerate(questions):
        if question.pk == question_id:
            current_question = question
            if ind != len(questions) - 1:
                next_question = questions[ind + 1]

    return render(
        request,
        "quizzes/display.html",
        {"quiz": quiz, "question": current_question, "next_question": next_question},
    )


def grade_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answer = question.get_answer()
    if answer is None:
        return render(request, "quizzes/partial.html", {"error": "Question must have an answer"}, status=422)
    is_correct = answer.is_correct(request.POST.get("answer"))
    return render(
        request,
        "quizzes/partial.html",
        {"is_correct": is_correct, "correct_answer": answer.correct_answer},
    )

src/quizzes/templates/quizzes/display.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Quiz: {{ quiz.name }}</title>
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'quizzes/style.css' %}">
</head>
<body>
    <div class="container">
    <h1>Quiz: {{ quiz.name }}</h1>

    <section class="question">
    {% if question %}
    <form id="question-form" action="{% url 'quizzes:grade_question' question.id %}" method="post">
        {% csrf_token %}

        <fieldset class="form-group">
            <legend>{{ question.prompt }}</legend>
            {% if question.freetextanswer %}
            <div class="form-group">
            <label for="answer">
            {% if question.freetextanswer.case_sensitive %}
            Type your answer in (capitalization matters!):
            {% else %}
            Type your answer in (don't worry about capitalization):
            {% endif %}
            </label>
            <input type="text" name="answer" class="form-control">
            </div>
            {% else %}
            {% for choice in question.multiplechoiceanswer.choices %}
            <div class="radio">
            <label>
                <input type="radio" name="answer" value="{{ choice }}">
                {{ choice}}
            </label>
            </div>
            {% endfor %}
            {% endif %}
        </fieldset>
        <button type="submit" class="btn btn-primary">Check answers</button>
    </form>

    <div id="question-feedback" style="margin-top:16px">
    </div>
    {% else %}
    Sorry, that question doesn't exist in this quiz.
    {% endif %}
    </section>

    {% if next_question %}
    <div style="margin-top:12px; font-size:16px">
    <a href="{% url 'quizzes:display_question' quiz.id next_question.id %}">→ Next question</a>
    </div>
    {% endif %}
    </div>

    <script>
    const form = document.getElementById("question-form");
    form.addEventListener("submit", (e) => {
        e.preventDefault();
        fetch(form.action, {method:'post', body: new FormData(form)})
            .then((response) => response.text())
            .then(text => {
                document.getElementById("question-feedback").innerHTML = text;
            });
    });
    </script>
</body>
</html>

src/quizzes/templates/quizzes/index.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Quizzes</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1>Quizzes</h1>
{% if quiz_list %}
    <ul>
    {% for quiz in quiz_list %}
        <li><a href="{% url 'quizzes:display_quiz' quiz.id %}">{{ quiz.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No quizzes are available.</p>
{% endif %}
    </div>

</body>
</html>

src/quizzes/templates/quizzes/partial.html
{% if error %}
<div class="alert alert-danger" role="alert">
  {{ error }}
</div>
{% else %}

{% if is_correct %}
✅ You got it!
{% else %}
❌ Sorry! The correct answer is {{ correct_answer }}
{% endif %}

{% endif %}